name: Java UI Automation CI

on:
  push:
    branches: [ Refactor ]
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 3. Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 4. Run tests with Maven
        working-directory: ./TutorialsNinja
        run: |
          mvn clean test -Dbrowser.type=chrome -Dbrowser.headless=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer=warn
        continue-on-error: true

      - name: 5. Set up Allure Commandline
        run: |
          wget https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.29.0/allure-commandline-2.29.0.zip
          
          sudo apt-get update -y && sudo apt-get install -y unzip
          
          unzip allure-commandline-2.29.0.zip -d ./allure-tool
          
          echo "$GITHUB_WORKSPACE/allure-tool/allure-2.29.0/bin" >> $GITHUB_PATH

      - name: 6. Generate Allure Report
        if: always()
        working-directory: ./TutorialsNinja
        run: |
          allure generate target/allure-results -c -o allure-report

      - name: 7. Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./TutorialsNinja/allure-report
          retention-days: 7

      - name: 8. Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TutorialsNinja/allure-report
          publish_branch: gh-pages